x-builder: &builder
  build:
    dockerfile: Dockerfile-builder
  volumes:
    # Source code:
    - ".:/go/src/jrouter"
    # GOCACHE:
    - "~/Library/Caches/go-build:/root/.cache/go-build"
    # GOMODCACHE:
    - "~/go/pkg/mod:/go/pkg/mod"
  working_dir: /go/src/jrouter
  # mage -keep needed since multiple concurrent instances of mage has racy
  # access to the same mage_output_file.go.
  # the outer call to mage usually cleans it up
  command: "go tool mage -keep binary"

services:
  build-arm64:
    <<: *builder
    platform: linux/arm64/v8

  build-amd64:
    <<: *builder
    platform: linux/amd64
